import type { ReactNode } from 'react';
import categoryNav from '@site/src/data/category-nav.json';
import styles from './styles.module.css';

type CategoryKey = keyof typeof categoryNav;

interface CategoryNavProps {
  category: CategoryKey;
}

/**
 * Auto-generated navigation list for category index pages
 * Uses data from category-nav.json (generated by scripts/generate-category-nav.js)
 */
export default function CategoryNav({ category }: CategoryNavProps): ReactNode {
  const pages = categoryNav[category];

  if (!pages || pages.length === 0) {
    return <p className={styles.empty}>No pages in this category yet.</p>;
  }

  return (
    <ul className={styles.navList}>
      {pages.map((page) => (
        <li key={page.docId} className={styles.navItem}>
          <a href={`/docs/${page.docId}`}>{page.title}</a>
        </li>
      ))}
    </ul>
  );
}
