M48
; DRILL file {KiCad 9.0.6} date 2026-01-11T21:04:51+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-11T21:04:51+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X-2.6Y-3.2
X12.2Y-95.8
X19.75Y-68.5
X23.8Y-22.3
X66.75Y-90.0
X72.5Y-3.2
X72.5Y-95.5
M30
