/**
 * Page assembly: frontmatter plus a serialized body, verified before it is
 * ever handed to the emitter.
 *
 * Frontmatter is a closed key set with JSON-encoded scalar values. YAML 1.2 is
 * a JSON superset, so `JSON.stringify` of a string is always a valid
 * double-quoted YAML scalar — that is the whole escaping story for the header,
 * and it means an evidence string can never terminate the block or introduce a
 * key.
 *
 * The generated-file marker is a YAML COMMENT inside that block, not an HTML
 * comment in the body: MDX has no `<!-- -->` comment syntax, so a body marker
 * would be a parse error, and a frontmatter KEY would surface in page metadata.
 */

import { fail } from "./errors.ts";
import { assertMdxSafe, serializeBody } from "./mdx.ts";
import type { SafeText } from "./text.ts";
import type { RootContent } from "mdast";

/**
 * Marker every generated page carries. The emitter refuses to delete a file
 * under its owned tree that does not carry it, so a stray hand-authored file
 * is reported rather than destroyed.
 */
export const GENERATED_MARKER =
  "# GENERATED by doc/component-docs — do not edit; run `pnpm generate:components`";

export type PageFrontmatter = {
  readonly title: SafeText;
  readonly description: SafeText;
  /** Sidebar ordering within its directory. */
  readonly sidebarPosition: number;
};

export type GeneratedPage = {
  /** POSIX-style path relative to the generated root, e.g. `records/al8860mp-13/index.mdx`. */
  readonly relativePath: string;
  readonly contents: string;
  /**
   * Every `EvidenceAnchor` id this page defines, and every link target it
   * emits — read off the body AST rather than the serialized text, so a link
   * label containing a bracket cannot be mistaken for a link.
   *
   * `core/links.ts` needs both to prove that what this page points at exists.
   * They are collected here because this is the only place that still holds
   * the AST: everything downstream sees `contents` and nothing else.
   */
  readonly anchors: readonly string[];
  readonly links: readonly string[];
};

const RELATIVE_PATH_PATTERN = /^(?:[a-z0-9][a-z0-9-]*\/)*[a-z0-9][a-z0-9-]*\.mdx$/u;

export function buildPage(
  relativePath: string,
  frontmatter: PageFrontmatter,
  body: readonly RootContent[],
): GeneratedPage {
  if (!RELATIVE_PATH_PATTERN.test(relativePath)) {
    fail("PATH_CONTAINMENT", `generated path ${relativePath} is not a permitted shape`, {
      relativePath,
    });
  }
  if (!Number.isInteger(frontmatter.sidebarPosition) || frontmatter.sidebarPosition < 0) {
    fail("UNSAFE_VALUE", "sidebar_position must be a non-negative integer", {
      relativePath,
      value: String(frontmatter.sidebarPosition),
    });
  }

  const serialized = serializeBody(body);
  assertMdxSafe(serialized, relativePath);

  const anchors: string[] = [];
  const links: string[] = [];
  collectReferences(body, anchors, links);

  const header = [
    "---",
    GENERATED_MARKER,
    `title: ${JSON.stringify(frontmatter.title)}`,
    `description: ${JSON.stringify(frontmatter.description)}`,
    `sidebar_position: ${frontmatter.sidebarPosition}`,
    "---",
  ].join("\n");

  return { relativePath, contents: `${header}\n\n${serialized}`, anchors, links };
}

/**
 * The subset of a node this walk cares about. mdast's own types do not cover
 * the MDX JSX nodes (`mdast-util-mdx` contributes those), and the builders in
 * `mdx.ts` already cast them into `RootContent`, so the walk reads the shape
 * structurally instead of re-deriving that union here.
 */
type WalkableNode = {
  readonly type?: string;
  readonly url?: string;
  readonly name?: string;
  readonly attributes?: readonly { readonly name?: string; readonly value?: unknown }[];
  readonly children?: readonly unknown[];
};

function collectReferences(
  nodes: readonly unknown[],
  anchors: string[],
  links: string[],
): void {
  for (const candidate of nodes) {
    const node = candidate as WalkableNode;
    if (node.type === "link" && typeof node.url === "string") {
      links.push(node.url);
    }
    if (node.name === "EvidenceAnchor") {
      for (const attribute of node.attributes ?? []) {
        if (attribute.name === "id" && typeof attribute.value === "string") {
          anchors.push(attribute.value);
        }
      }
    }
    if (node.children !== undefined) {
      collectReferences(node.children, anchors, links);
    }
  }
}

/** Whether a file on disk is one this generator owns. */
export function isGeneratedContents(contents: string): boolean {
  return contents.startsWith(`---\n${GENERATED_MARKER}\n`);
}
