import type { ReactNode } from 'react';
import useGlobalData from '@docusaurus/useGlobalData';
import sidebars from '@site/sidebars';

type SidebarItem =
  | string
  | {
      type: string;
      label: string;
      items?: SidebarItem[];
      link?: { id: string };
    };

/**
 * Auto-generate display label from sidebar ID
 * Examples:
 *   inboxSidebar → INBOX
 *   componentsSidebar → Components
 *   howToSidebar → HowTo
 *   learningSidebar → Learning
 */
function generateLabel(sidebarId: string): string {
  // Remove "Sidebar" suffix
  const name = sidebarId.replace(/Sidebar$/, '');

  // Special case: inbox → INBOX (all caps)
  if (name.toLowerCase() === 'inbox') {
    return 'INBOX';
  }

  // Convert camelCase to Title Case
  // howTo → HowTo, learning → Learning
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/**
 * Render a single sidebar item (doc link or category)
 */
function renderSidebarItem(item: SidebarItem, docTitles: Record<string, string>): ReactNode {
  // String item (doc ID)
  if (typeof item === 'string') {
    const title = docTitles[item] || item;
    return (
      <li key={item}>
        <a href={`/docs/${item}`}>{title}</a>
      </li>
    );
  }

  // Category with items
  if (
    typeof item === 'object' &&
    'type' in item &&
    item.type === 'category' &&
    'items' in item &&
    Array.isArray(item.items)
  ) {
    return (
      <li key={item.label}>
        <strong>{item.label}:</strong>
        <ul>{item.items.map((subItem: SidebarItem) => renderSidebarItem(subItem, docTitles))}</ul>
      </li>
    );
  }

  // Autogenerated
  if (typeof item === 'object' && 'type' in item && item.type === 'autogenerated') {
    return null;
  }

  return null;
}

interface DocMetadata {
  id: string;
  title: string;
}

interface DocsVersion {
  docs: Record<string, DocMetadata>;
}

interface DocsPluginData {
  versions: DocsVersion[];
}

export default function DocsSitemap(): ReactNode {
  // Get all docs metadata from Docusaurus (auto-generated, always up-to-date!)
  const globalData = useGlobalData();

  // Extract doc titles from metadata
  // The docs plugin data is under 'docusaurus-plugin-content-docs'
  const docsPluginData = globalData['docusaurus-plugin-content-docs'] as Record<
    string,
    DocsPluginData
  >;
  const docsData = docsPluginData?.['default'];
  const docTitles: Record<string, string> = {};

  if (docsData?.versions?.[0]?.docs) {
    Object.values(docsData.versions[0].docs).forEach((doc: DocMetadata) => {
      docTitles[doc.id] = doc.title;
    });
  }

  // Auto-generate sidebar list from sidebars.js (preserves object key order)
  const sidebarEntries = Object.entries(sidebars);

  return (
    <section style={{ marginTop: '3rem' }}>
      <h2>Documentation Index</h2>
      <p style={{ fontSize: '0.9rem', color: '#666', marginBottom: '1rem' }}>
        Complete list of all documentation pages (auto-generated from sidebars.js)
      </p>

      {sidebarEntries.map(([sidebarId, sidebarItems]) => {
        const label = generateLabel(sidebarId);

        if (!sidebarItems || !Array.isArray(sidebarItems)) {
          return null;
        }

        return (
          <details key={sidebarId} open style={{ marginBottom: '1rem' }}>
            <summary
              style={{
                fontSize: '1.3rem',
                fontWeight: '600',
                padding: '0.5rem 0',
                cursor: 'pointer',
                userSelect: 'none',
                listStyle: 'none',
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <span style={{ marginRight: '0.5rem' }}>▶</span>
              {label}
            </summary>
            <ul style={{ marginTop: '0.5rem' }}>
              {(sidebarItems as SidebarItem[]).map((item) => renderSidebarItem(item, docTitles))}
            </ul>
          </details>
        );
      })}

      <style>{`
        details[open] > summary > span {
          transform: rotate(90deg);
          display: inline-block;
        }
        details > summary {
          transition: all 0.2s ease;
        }
        details > summary:hover {
          color: var(--ifm-color-primary);
        }
        details > summary > span {
          transition: transform 0.2s ease;
          font-size: 0.8em;
        }
      `}</style>
    </section>
  );
}
